### PR TITLE
add support for Widget Key.

### PR DESCRIPTION
**Pull request by jinxul**

### CODE REVIEW

**Comment by tomwyr** [comment]
Is there any reason that the key should be passed strictly to `ListView` builder and not to `super` constructor of the widget itself?

**Comment by jinxul** [comment]
when manipulating list items (ie removing an item) sometimes (if not always) the wrong item will be removed/changed in UI. apparently for it to work the listview itself needs to have a Key.

**Comment by tomwyr** [comment]
This doesn't seem to happen to me. Could provide some basic example that shows the issue?

**Comment by jinxul** [comment]
the problem seems to happen when `builder` is also a `StatefulWidget`. 

for example:
[code.zip](https://github.com/tomwyr/drag-list/files/3902971/code.zip)

**Pull request merged**
